### ISSUE TITLE
"display: inline-block;" behaves the "display: block;"

### ISSUE THREAD

**Issue by jcorby24** [brave/browser-laptop-releases#3]
Don't know if it's just the beta/pre-release binary or present in the developer git self-compiled version as well. 

An example, use chrome to browse - http://www.arco.co.uk/
And then give it a whirl with Brave. 

An example of the CSS rule that isn't behaving correctly - 

`#md-container a {
    display: inline-block;
}`

**Comment by jcorby24** [comment]
Investigating this more, for some reason in Brave only it removes the CSS rule for some reason? If you apply inline-block directly it will behave correctly.

**Comment by jcorby24** [comment]
A final investigation shows the styling for there inline-block rule to be coming from a CSS file named "adverts.css" which I guess Brave removes as per it's advert blocking nature. 

Not really sure how to get around that, might be one for their own devs to sort out.

**Comment by bbondy** [comment]
I think you want the https://github.com/brave/browser-laptop repo. This is for electron-prebuilt building.
We can add a filter rule to fix sites like that if needed on a per domain basis, but please report it to that repo. Thanks.
